name: openduck
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - yank=0.25.2
  - pdbfixer=1.7
  - openff-toolkit=0.9.0
  - parmed=3.4.3
  - cudatoolkit=11.7.0
  - openmm=7.5
  - openmmforcefields=0.9.0
  - ambertools=22.0
  - seaborn=0.12
